language: php

branches:
  only:
    - /.*/

php:
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - mkdir build
  - mkdir test/attachments/dir/dirdept
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpstan analyse src/ --level=6
  - ./vendor/bin/phpunit --coverage-clover build/clover.xml
  - ./vendor/bin/infection --threads=4 --min-msi=80

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml

sudo: false
